services:
  pvw:
    image: h3lioviz:latest
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: test-data/
        target: /data
    restart: always
    environment:
      - SERVER_NAME=127.0.0.1
      - PROTOCOL=ws
      # - S3_BUCKET_NAME=NA Local deployments cannot access AWS resources without credentials
      # - TABLE_NAME=NA     Same as above
      # - INSTANCE_REGION=NASame as above (TODO: Cannot do instance stuff on the instance itself)
      # - INSTANCE_ID       Same as above (TODO: Same as above)
