version: '3.2'

services:
  pvw:
    # image: public.ecr.aws/enlil/paraview_web_repo:${PVW_IMAGE_TAG:-pvw-h3lioviz-osmesa}
    image: pvw-h3lioviz-osmesa
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ${PVW_DATA:-/data/pv-data}
        target: /data
    restart: always
    environment:
      - SERVER_NAME=${SERVER_NAME:-127.0.0.1:8080}
      - PROTOCOL=${PROTOCOL:-ws}
